### PR TITLE
Added data field to traversals in dsl specification

### PR DESCRIPTION
**Pull request by rickteuthof**
Added a field in the dsl specification in which the user can specify their own data used in the traversal. This is done by reusing the 'Attr' type. It is unsure if this is the best way of using this.

### CODE REVIEW

**Comment by leegbestand** [comment]
Looks good, but how are user-defined types handled? 
For example:
travdata = {
    int a = 0,
   smap_t mymap = smap_create(10) ?? // How is this handled? 
}
In the example, need to know what smap_create is, you can extern it, but what is 10? Is that an Int, size_t or? So, probably need to know what include statement is required for the smap_t type.

**Comment by rickteuthof** [comment]
It doesn't appear that we support smaps in general as of now, wouldn't this require an extension for the attr in the yacc file?

Concerning error handling, I'm currently adding this to check.c

**Comment by leegbestand** [comment]
In the typed backend, the "info" structure is defined by the user, so they can put whatever they want in it.

**Comment by rickteuthof** [comment]
In that case we should have to expand the attr in the yacc file, something like `attrhead '=' constructorname '(' arglist ')'`

Wouldn't this cause problems with serialisation though?

**Comment by rickteuthof** [comment]
Added new TravData type. TravData can have two kinds of values, a primitive type, or a user defined type. User defined type must have an include file specified along with its constructor and constructor arguments. check.c has a check for it in the same style as attribute checking

**Comment by rickteuthof** [comment]
One problem with typechecking, should typechecking be done by the user with generated code? Or should check.c check if the type actually exists in the file specified?

**Comment by leegbestand** [comment]
Type checking for the traversal info is probably best done by the C compiler. Because, lib/smap might include a file which actually defines the smap_t, so then you need to run cpp, which requires you to know include paths and so on. It can become rather complex and requires re-implementing stuff the C compiler does. 

The issue is that there can be compiler errors in generated code. 

Two options I see for this:
1): Do not allow user defined types in the DSL and require the user to define their own trav_data when they want to use a user defined type. Con for this is that trav_data is defined in two locations, but no compiler errors in generated  code.
2): Specify something like unsafe before the trav_data is defined to indicate that the region does  something out of the control of the framework. This option provides a clear distinction between trav_data that is fully checked by us and trav_data that is not. The con for this is that there are still compiler errors in generated code, but trav_data is in one place and should make 'unsafe' places easier to spot.

**Comment by rickteuthof** [comment]
I've thought about this, and i'm personally for option 2. If the user wants to use their own data structures, then they should be responsible for checking their own types. An 'unsafe' keyword would be a proper solution i think.

**Comment by rickteuthof** [comment]
One thing i haven't taken into account is specifying a suitable destructor, so i will add something for this as well

**Comment by rickteuthof** [comment]
Maybe it would be a better idea to only generate wrapper constructors and destructors which the user can define themselves? Then we could just only have declarations in the AST specification, which would keep it simple to use. With this in mind, the code would look something like this:

For the AST specification:
```
traversal Print {
    prefix = PRT,
    travdata = {
        int test.
        smap_t testmap { "lib/smap.h" },
        imap_t testmap2 { "lib/imap.h" }
    }
};
```

For the code
```
...
#include "lib/smap.h"
#include "lib/imap.h"
...
smap_t *print_testmap_init() {
    <user defined construction here>
}
imap_t *print_testmap2_init() {
    <user defined construction here>
}
Trav *print_init() {
    int test = <somevalue>;
    smap_t *testmap = print_testmap_init();
    imap_t *testmap2 = print_testmap2_init();
}
```

We could also just only generate the `print_init` function and define the user defined typed variables directly to lessen code explosion in case of a lot of user generated traversal attributes, but this is just a thought.

**Comment by leegbestand** [comment]
A  wrapper ctor and dtor provide the required flexibility. What if we ignore the specific ctors and dtors and have a traversal specific ctor/dtor when a value is not specified. 

So, in the example:
traversal Print {
    prefix = PRT,
    travdata = {
        int test = 0,
        unsafe smap_t *testmap { "lib/smap.h" },
        unsafe imap_t *testmap2 { "lib/imap.h" }
    }
};

TravData print_init(Trav_Data *ctx) {
// User has to fill it in, ctx.test is already set to 0, the smap_t and imap_t are initialized to NULL, but because no value is specifiied for the maps and thus require an init call. 
}

If you have something like this:
traversal Print {
    prefix = PRT,
    travdata = {
        int test = 0,
    }
};
You do not have a init call, because you specified the init values already.

**Comment by rickteuthof** [comment]
Implemented this suggestion, merging with master

**Comment by rickteuthof** [comment]
Fixed merge mistake

**Pull request merged**
